DeveloperAcademy-POSTECH/MacC-Team-DGC

- Carmunication.xcodeproj/project.pbxproj
- Carmunication/Controllers/LoginViewController.swift
- Carmunication/Controllers/MyPage/MyPageViewController.swift
- Carmunication/Controllers/MyPage/SettingsViewController.swift
- Carmunication/Models/KeychainItem.swift
- Carmunication/SceneDelegate.swift
- 로그인 되어 있다면 바로 메인 탭 뷰로 진입
- 로그인 되어 있지 않다면 로그인 화면으로 진입
👉 `Auth.auth().currentUser` 코드로 파이어베이스 서버에서 바로 사용자의 로그인 정보를 확인할 수 있습니다. (https://firebase.google.com/docs/auth/ios/manage-users?hl=ko#get_the_currently_signed-in_user)
- 해당 코드를 SceneDelegate의 scene(_:willConnectTo:options:) 메소드 내부에 작성해서 처음에 어느 화면으로 진입할지를 결정하도록 했습니다.
- 당장은 키체인의 uid 값을 사용하지 않지만 이후 파이어베이스 DB에 요청을 할 때 유저를 식별하려면 필요할 것 같아 구현했습니다.
- Keychain에 저장되는 item을 관리해주는 KeychainItem.swift 파일을 생성했습니다.
- 로그인 시에는 uid값을 키체인에 저장
- 로그아웃, 회원 탈퇴 시에는 키체인의 uid값을 삭제
Issue Number: #13 
Resolved: #13
> [Feat] 유저 로그인 정보에 따른 처리 및 저장

- .github/workflows/swiftlint.yml
- .swiftlint.yml
Pull Request 요청시 SwiftLint를 동작시켜 코드를 검사하는 환경을 세팅했습니다.
위 사진처럼 레포당 사용량 한도(2000분/월)가 있고 초과시에는 비용이 청구될 수도 있어서 PR시에만 동작하도록 설정했습니다.
건당 1분 내외로 2000 PR 작성시 사용량을 전부 사용할테니 넉넉할 듯합니다.
SwiftLint 동작시 아래 항목들은 무시되도록 추가했습니다.
- parameter 5개 초과시 경고 (이 항목은 추후 코드 수정되면 삭제하겠습니다)
- 불필요한 override 작성시 경고
빌드확인하는 환경도 세팅하려 했으나 macOS의 경우 linux의 10배로 시간측정이 된다고 해서 없던일로... 😅
Issue Number: #32 
Resolved: #32
> [Chore] PR 요청시 SwiftLint 동작하도록 환경 세팅

- Carmunication/Extensions/SessionStartView+Extension.swift
- Carmunication/Views/SessionStart/SessionStartView.swift
SessionStartView에 대한 리팩토링 작업입니다.
Issue Number: #40
Resolved: #40 
이슈에서도 말씀드렸지만, 다음과 같은 참고 사항들이 있습니다.
- Model 객체 옵셔널 및 Date 형식으로 변경 --> 해당 모델은 DB 형식이 나오면 수정하겠습니당 (어차피 DB 형식에 따라 바뀔 것이기 때문)
- setupConstraints()에 대한 설정 또한 우선 기능 개발을 마무리 한 뒤에 하는 것이 좋지 않을,,까,,, 생각입니다. (물론 시간이 된다면 작업을 진행할 것 같은데, 우선적으로 해야할 일들부터 하는 것이,,)
- 그리고 컴포넌트가 많아서 파일 길이가 너무 길어지는데, 하나의 extension 파일에 메서드들을 모두 저장하는 것이 나을지, 아니면 기준에 따라 extension 파일을 2개 정도로 분리하여 관리하는 것이 좋을 지 고민인데, 여러분들의 생각을 듣고싶습니다!
- 위의 사항들은 다음 이슈 때 SessionStartView의 TODO에 작성해놓겠습니다.
> [Refactor] SessionStartView 리팩토링 

- Carmunication.xcodeproj/project.pbxproj
- Carmunication/Controllers/LoginViewController.swift
- Carmunication/Controllers/MyPage/SettingsViewController.swift
- Carmunication/Models/DummyData/DummyData.swift
- Carmunication/Models/DummyData/User.swift
아래와 같이 유저 정보가 추가됩니다. (프로필 사진, 친구 목록, 그룹 목록은 일시적으로 삭제했고 추가 예정)
TO 레이
마이페이지에서 유저네임 수정시 DB에서 업데이트하는 작업도 추후 필요할 것 같아요 🥹
Issue Number: #39 
Resolved: #39
> [Feat] 애플 로그인, 회원탈퇴시 DB 갱신

- Carmunication.xcodeproj/project.pbxproj
- Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
- Carmunication/Controllers/SessionList/GroupAdd/SelectAddressViewController.swift
- Carmunication/Controllers/SessionList/GroupAdd/SelectDetailPointMapViewController.swift
- Carmunication/Controllers/SessionList/GroupAdd/SelectStartTimeViewController.swift
- Carmunication/Extensions/Date+Extension.swift
- Carmunication/Extensions/String+Extension.swift
- Carmunication/Models/DummyData/Point2.swift
- Carmunication/Views/SessionList/Cell/GroupAddTableViewCell.swift
- Carmunication/Views/SessionList/GroupAdd/SelectStartTimeModalView.swift
상세 모달(시간 설정 화면)과 주소 설정 시 데이터를 GroupAddViewController로 전달하는 작업을 마쳤습니다.
또한 GroupAdd 데이터 유효성 관련 Alert 처리도 완료하였습니다.
이전의 코드 리뷰에서 요청 주신 사항을 반영하였습니다.
Point2 모델의 경우, Point 모델과 병합해야 합니다. 추후 작업을 진행하도록 하겠습니다.
Issue Number: #60 
Resolved: #74 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/e01cf5b9-a902-4a53-92a4-11642b660e33
> [Feat] 이전 화면, 다음화면 간 데이터 전달 구현 

- Carmunication/Controllers/SessionStart/SessionStartViewController.swift
- Carmunication/Models/DummyData/Group.swift
- Carmunication/Views/SessionStart/SessionStartView.swift
- 운전자일 때와 동승자일 때 버튼을 달라지게 하였습니다. 
Issue Number: #71 
Resolved: #71 
[iPhone SE]
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/4f6e8e45-7dc2-4278-8130-398e3bc4c86b
<br>
<br>
[iPhone 12 mini]
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/6aa8c26b-66e2-4722-af08-8e603b24607a
<br>
<br>
[iPhone 14]
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/2a90cfd9-dbd6-49ba-9090-8a53f17d0c54
> [Design] SessionStartView 데이터 없을 때의 화면 생성 및 동승자 화면 구성

- .gitignore
- Carmunication.xcodeproj/project.pbxproj
- Carmunication/AppDelegate.swift
- Carmunication/Carmunication.entitlements
- Carmunication/Controllers/LoginViewController.swift
- Carmunication/Controllers/MainTabBarViewController.swift
- Carmunication/Controllers/MyPage/FriendAddViewController.swift
- Carmunication/Controllers/MyPage/FriendListViewController.swift
- Carmunication/Info.plist
- Carmunication/Models/DummyData/DummyData.swift
- Carmunication/Models/DummyData/User.swift
- 디바이스 토큰값이 user 데이터에 추가되는 작업을 진행했습니다.
- REVERSED_CLIENT_ID 값을 보안처리해주었습니다.
Issue Number: #79 
Resolved: #79 
해당 사항은 좀 중요한 것 같아, 모든 분들에게 리뷰를 날렸습니다,,!
여러 모로 많이 배운 것 같네요,,, 😇
> [Feat] User에 디바이스 토큰값 추가

- Carmunication.xcodeproj/project.pbxproj
- Carmunication/Controllers/MyPage/FriendListViewController.swift
- Carmunication/Views/MyPage/FriendListView.swift
Issue Number: #84
Resolved: #84
- PR 병합을 기다리면서 친구가 없을 때의 친구 목록 화면을 구현해놓았습니다.
- `FriendListViewController`에서 친구 목록을 불러온 뒤, `friendList` 배열에 들어 있는 값의 수를 확인해서 친구 목록 테이블 뷰를 보여줄 지 다른 화면을 보여줄 지 결정됩니다.
- 가운데 회색 뷰는 아직 확정되지 않은 디자인입니다.
> [Design] 친구 없을 때 친구관리 화면 구성

- Carmunication/Controllers/LoginViewController.swift
- Carmunication/Controllers/MyPage/FriendAddViewController.swift
- Carmunication/Controllers/MyPage/FriendListViewController.swift
- Carmunication/Controllers/MyPage/MyPageViewController.swift
- Carmunication/Models/DummyData/User.swift
Issue Number: #83
Resolved: #83
- User 모델의 imageURL과 friends 프로퍼티 타입을 옵셔널로 변경해주었습니다.
- 변경된 타입에 맞게 해당 객체를 초기화하거나, DB로부터 불러오는 코드를 옵셔널 바인딩 처리하도록 수정했습니다.
> [Fix] User 모델 필수 프로퍼티 옵셔널 타입으로 변경

- Carmunication.xcodeproj/project.pbxproj
- Carmunication/Controllers/SessionStart/SessionStartViewController.swift
- Carmunication/Views/SessionStart/SessionStartMidNoGroupView.swift
- 그룹이 없을 때 나타나는 화면을 생성하였습니다.
Issue Number: #88 
Resolved: #88 
- 하지만 아직 화면에 있는 이미지가 확정되지 않은 것 같아 SF Symbol로 대체해놓았습니다.
[iPhone SE]
<br>
<br>
[iPhone 12 mini]
<br>
<br>
[iPhone 14]
> [Design] 그룹이 없을 떄 나타나는 화면 디자인

- Carmunication/Controllers/SessionStart/SessionStartViewController.swift
- 버튼 클릭시 버튼 색상 변경 -> 클릭 시 alert 창 -> 클릭 시 맵뷰 로직을 완성해놓았습니다.
- 빨간 버튼으로 변경될 때 라벨에 인원수가 표시되도록 변경되는 부분은 추후에 생성해놔야 할 것 같습니다
Issue Number: #77 
Resolved: #77 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/475d756e-ba33-4ed7-aa71-9ae0a20bc2fa
> [Feat] 운전자가 버튼 클릭으로 맵뷰까지 이동하는 로직 생성

- Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
그룹 만들기에 필요한 기능을 모두 구현했습니다.
탑승자로 선택된 크루를 이제 모달에서 넣고 빼고가 가능해졌습니다.
추가적으로 그룹 이름 미입력시 걸러주는 Alert를 추가했습니다.
현재 진입 초기에 유저의 이미지를 불러오는 시간이 약 1초간 걸려서 로딩이 지연되는 상황은
추후, 공통 작업 후 버그를 수정할 예정입니다.
Issue Number: #78 
Resolved: #100 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/cdf074cf-1e99-4b79-a343-256f8a731a82
> [Feat] 크루 만들기 상세 기능 최종 구현

- .github/workflows/swiftlint.yml
현재는 PR시 전체 코드에 대해 린트 확인 작업을 하고 있는데, 수정분에 대해서만 확인하도록 변경합니다
Issue Number: #108 
Resolved: #108 
> [Chore] PR시 수정분에 대해서만 린트 확인하도록 수정

- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Models/DummyData/Group.swift
- Carmu/Sources/Models/DummyData/Point.swift
- Carmu/Sources/Models/DummyData/Session.swift
- Carmu/Sources/Models/DummyData/User.swift
- Carmu/Sources/Views/SessionStart/SessionStartMidView.swift
- Group, Point, Session 관련 모델 수정
Issue Number: #111 
Resolved: #111 
혹시 의문이신 점이 있다면 언제든지 물어봐주세요 !!!!
해당 부분은 모든 분들께서 확인해보시면 좋을 것 같아 모두 리뷰어에 포함시켰습니다.
특히 본인의 부분과 연관이 있으신 분들은 확인 한 번 더 확인해주시면 감사하겠습니다 ㅎㅎ,,!
[User]
<br>
<br>
[Group]
<br>
<br>
[Point]
<br>
<br>
[Session]
<br>
<br>
[예시]
> [Feat] ERD 수정 

- Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- 친구 추가를 보냈을 시 친구에게 친구가 추가되었다는 서버 푸시를 보냅니다.
Issue Number: #119 
Resolved: #119 
> [Feat] 친구 추가되었을 시 친구에게 서버 푸시

- Carmu/Sources/Controllers/SessionStart/SessionMapView/NoticeLateViewController.swift
- Carmu/Sources/Controllers/SessionStart/SessionMapView/SessionMapViewController.swift
- Carmu/Sources/Views/SessionStart/SessionStartMidView.swift
- 지각 알림 보냈을 시 토스트 메세지 나타나기
Resolved: #138 
- presenting과 같은 것에 대해 다시 공부해야겠군요,, (Thanks Uni,,)
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/457614a9-cfee-4ef4-89a5-d23f4dfdd6d2
> [Feat] 지각 메세지 보냈을 시 토스트 알림 보내기

- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- 푸시 알림을 보낼때 여러 번의 알림이 가는 경우를 수정해주었습니다.
- 서버 푸시를 보낼 때 소리와 진동이 울리는 부분은 백엔드 부분에서 수정을 해주었습니다.
Resolved: #141 
> [Refactor] 서버 푸시 관련 코드 수정

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/CrewMake/InviteCodeInputViewController.swift
- Carmu/Sources/Extensions/UIImage+Extension.swift
- Carmu/Sources/Models/Color/SemanticColor.swift
- Carmu/Sources/SceneDelegate.swift
- Carmu/Sources/Views/CrewMake/InviteCodeInputView.swift
- Carmu/Sources/Views/CrewMake/PositionSelectView.swift
공유 코드 입력 화면에 대한 구현을 끝냈습니다.
텍스트 필드 하단의 라벨 등장 로직은 추후 구현 예정입니다.
키보드 관련 액션도 구현 완료했습니다.
Resolved: #144 
> [Feat] 크루 생성 - 공유 초대코드 입력 화면 구현(동승자)

- Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
- Carmu/Sources/Models/DTO/Crew.swift
- Carmu/Sources/Models/DTO/Point.swift
- Carmu/Sources/Utils/FirebaseManager.swift
크루 데이터를 운전자 크루 생성화면 중 FinalConfirm 화면에서 업로드 하도록 구현했습니다.
현재 Model 중 Crew와 Point에 대대적인 수정이 있었습니다.
주석을 달아 각 속성별로 담당하는 역할을 작성해두었습니다. 참고해주시기 바랍니다.
Resolved: #183 
> [Feat] 운전자의 크루생성 마지막 화면에서 더미 크루 데이터 Firebase DB에 저장

- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
- 따로가기 버튼을 클릭했을 때의 로직을 구현하였습니다.
- 운전자와 동승자의 경우를 분리하여 구현해놓았습니다.
Resolved: #191 
[운전자]
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/55767a01-ca20-4d2d-8e0d-5bee88486afe
<br>
<br>
[동승자]
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/bc127a81-47eb-4490-bc7e-14e4766aa2ff
> [Feat] 동승자가 따로 가요를 클릭했을 때의 화면

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
- Carmu/Sources/SceneDelegate.swift
- Carmu/Sources/Utils/ButtonComponent/RightNavigationBarButton.swift
- Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
최종 확인 화면을 구현했습니다.
요일 버튼의 경우, 너비가 텍스트에 따라 크기가 설정되도록 하였습니다.
아직 수정하기 버튼을 눌렀을 때의 액션은 구현하지 않았습니다. 추후, 작업후 연결 예정입니다.
Resolved: #155 
> [Feat] 크루 생성 - 최종 확인 화면 구현(운전자)

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Models/DTO/Crew.swift
- Carmu/Sources/SceneDelegate.swift
- Carmu/Sources/Views/SessionStart/CrewCollectionViewCell.swift
- Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
- 앞면 뷰를 배치하였습니다.
- 인원이 4명 이하일 때는 가운데 정렬을 통해 인원들이 배치되도록 하였고, 5명 이상일 때는 2줄로 인원이 배치되도록 하였습니다.
- Status에 **sessionStart**라는 케이스를 포함시켜주었습니다. 해당 케이스는 세션이 실제로 시작되었을 때의 Status로 사용하고자 지정하였습니다.
- 운전자가 함께하기를 클릭하지 않았을 때에는 "Zzz.."로 보이지만, 함께하기를 클릭하였을 때엔 "미응답"으로 구현해주었습니다.
Resolved: #207 
해당 영상에 나오는 데이터는 더미 데이터입니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/992e919c-b5f8-408f-bc6d-0b244a1378be
> [Design] 앞면 뷰 인원 배치

- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Models/DTO/Crew.swift
- Carmu/Sources/Views/SessionStart/CrewCollectionViewCell.swift
- Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
- Carmu/Sources/Views/SessionStart/SessionStartView.swift
- 운행해요 -> 카풀 시작하기 클릭 시 맵뷰 -> 뒤로 나갔다오면 "지도 보기"의 텍스트로 보이는 로직 설정
- 만약 응답자가 없다면 버튼 비활성화
Resolved: #212 
화질은 용량이슈로 줄였습니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/c5f65988-5fda-4241-83fe-aebaf2dcc33c
> [Feat] 운행해요 -> 맵뷰 관련 로직 구현 (운전자)

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/LoginViewController.swift
- Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
- Carmu/Sources/Controllers/MyPage/Settings/PrivacyViewController.swift
- Carmu/Sources/Controllers/MyPage/Settings/QuestionDetailViewController.swift
- Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
- Carmu/Sources/Views/MyPage/Settings/InquiryView.swift
- Carmu/Sources/Views/MyPage/Settings/PrivacyView.swift
- Carmu/Sources/Views/MyPage/Settings/QuestionDetailView.swift
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/929be356-4ff8-43f0-ac0b-0b781123d361
- 자주 묻는 질문 상세화면으로 넘어갈 때 질문별로 다르게 보여주는 처리는 추후 진행하겠습니다.
Issue Number: #214
Resolved: #214
> [Design] 설정 화면 뷰 구성

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
- Carmu/Sources/SceneDelegate.swift
- Carmu/Sources/Utils/ButtonComponent/StopoverSelectButton.swift
- Carmu/Sources/Views/MyPage/CrewEdit/CrewEditView.swift
- Carmu/Sources/Views/MyPage/CrewEdit/CrewInfoCheckView.swift
- 일단 Crew.swift의 더미데이터(`crewData`)를 반영하도록 했습니다. 로직은 작성된 상태니 추후 DB 데이터로 불러오도록 수정하면 될 것같습니다.
- 추가로 크루 편집 화면 관련 파일을 추가해놨습니다. (편집 기능 구현은 다음 작업에서 진행하겠습니다.)
- 코드가 조금 난잡한 감이 있는데 일단 빠른 구현이 중요하니 추후 리팩토링 해보겠습니다...
Issue Number: #228
Resolved: #228
- crewData의 데이터 내용을 바꿔서 확인해본 화면
> [Feat] 마이페이지 크루 정보 확인 화면 데이터 연결

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
- Carmu/Sources/Models/DTO/Crew.swift
- Carmu/Sources/Models/DTO/Point.swift
- Carmu/Sources/SceneDelegate.swift
- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
- Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointView.swift
- Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
크루 생성시 실제 생성한 데이터들을 Firebase에 업로드 하는 기능을 구현했습니다.
실제 생성한 데이터를 토대로 각 뷰에서 보이는 것들이 달라지게 되었습니다.
또한 경유지 설정시 예상 경로를 표시하고, 그 위에 경유지 마커를 하나씩 추가하는 기능을 구현했습니다.
그리고 최초 그룹 생성한 이후에는 SessionStartVC가 보이도록 로직을 변경했습니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/3eb795ff-f100-41e5-a719-2e478635d2df
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/de75d27f-8c2c-4ef0-9c4d-76512e5cb58f
현재 수정하기 뷰가 구현되지 않았습니다. 제일 마지막에 구현할 예정입니다.
현재 수정해야 할 부분은 아래와 같습니다.
- 동승자 그룹 코드 확인 후 해당 크루에 등록하는 로직 추가
- 출발, 도착지 설정 -> 주소 설정 뷰 레이아웃 수정
- 출발 도착지 설정 뷰 하위 주소 설정 - 상세 위치 설정 버벅이는 버그 처리
- 경유지 설정 -> 동적 스택뷰로 수정
- NextButton 유효성 …
> [Feat] 크루 생성 화면 실 데이터 생성 작업

- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
- 현재 빌드 시 오류가 나고 있기 때문에 HOTFIX로 빠르게 올립니다.
Issue Number: #232
Resolved: #
> [HOTFIX] #232 머지 이후 옵셔널 처리 수정

- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- sessionStartViewController에 대한 리팩토링입니다.
1. 운전자일 때 - waiting, accept, decline, sessionStart,
2. 동승자일 때 - waiting, accept, decline, sessionStart
로 분리하였습니다.
Resolved: #227 
> [Refactor] SessionStartViewController 리팩토링

- Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
- Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
동승자 플로우 진행 시 그룹 코드를 입력하면 유효한지 체크하고, 경유지를 선택하면 크루의 정보에 유저 정보를 업데이트 하는 작업을 진행했습니다.
하단의 Firebase DB 스크린샷 참고하시면 되겠습니다.
이제 기본 생성 데이터 Create 작업이 끝났습니다!
Resolved: #235 
> [Feat] 동승자 그룹 코드 확인 후 해당 크루에 등록하는 로직 추가

- Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
- Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
- Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
- Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectView.swift
- Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapView.swift
- Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectView.swift
- Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectView.swift
- Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectModalView.swift
- Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
NextButton 형식으로 nextButton을 모두 설정하였고, 빈값 체크를 통해 nextButton을 enable 시켜주는 로직을 구현했습니다.
Resolved: #238 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/9e57fa87-c809-4103-bfee-30042184e2ed
> [Feat] NextButton 유효성 검사 후 enable 처리 

- Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
- Carmu/Sources/SceneDelegate.swift
로그인 여부에 따라서 rootVC를 바꿔주는 로직을 구현완료했습니다.
SceneDelegate의 authStateDidChangeHandle을 통해 Auth.auth()의 상태 변화를 감지하고 updateRootViewController()를 실행합니다.
Resolved: #239 
> [Feat] SceneDelegate Auth 변수 @State 처럼 기능하도록 변경

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/LoginViewController.swift
- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
- Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Models/DTO/Crew.swift
- Carmu/Sources/Models/DTO/CrewStatus.swift
- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
- Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
- Carmu/Sources/Views/SessionStart/StopoverInfoLeftView.swift
- Carmu/Sources/Views/SessionStart/StopoverInfoRightView.swift
- Firebase에서 데이터를 불러와 화면에 나타내주었습니다.
- Async / await를 사용하여 불러오도록 변경하였습니다.
- 현재는 카풀 이름, 총 인원 수를 불러오고 있습니다.
- 데이터가 로딩되지 않았을 때에는 로딩 화면이 표시되도록 하였습니다.
- crewStatus 모델을 새로 생성하였습니다. 추후에 이 모델을 기반으로 변경할 예정입니다.
- collectionView는 crewStatus 모델을 변경 후에 개발할 예정입니다.
Resolved: #236 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/b814058c-2dbe-4848-a951-9758fbd008f3
> [Feat] Firebase 연동 확인, 크루 생성까지의 플로우 확인, 실제 데이터로 수정 - 운전자

- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectAddressViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
- Carmu/Sources/Utils/ButtonComponent/AddressSelectButtonView.swift
- Carmu/Sources/Views/CrewMake/Driver/Cell/DefaultAddressTableViewCell.swift
- Carmu/Sources/Views/CrewMake/Driver/Cell/SelectAddressTableViewCell.swift
- Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectAddressView.swift
- Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapView.swift
두 개의 뷰에 대한 디자인 수정을 완료했습니다. 또한 버그도 수정했습니다.
분당수서로 문제의 경우, 초기에 화면에서 잠깐 떴다가 제대로된 주소로 변경이 되는데, 이부분은 로딩뷰를 넣어 해결하도록 하겠습니다.
진짜 끝
Resolved: #242 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/861c9e47-d8ef-4d81-8729-50d2177ba09f
> [Design] 주소 검색, 상세 위치 설정뷰(출발/도착지 하위) 디자인 수정

- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
- Carmu/Sources/Views/MyPage/CrewEdit/CrewEditView.swift
- Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/AddressEditButton.swift
- Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointEditView.swift
- Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointType.swift
- 동적으로 경유지를 넣었다가 빼는 문제 때문에 해당 PR 이후 크루 편집 화면에 대해서 테이블뷰로 변경하는 리팩토링 작업이 예정돼 있습니다.
- 아직 데이터도 이상하게 넘어가고 있는 상태라서, 이번 PR은 "그렇구나" 정도로만 확인해주시고 넘어가주시면 될 것 같습니다. (어차피 대대적으로 수정될 코드)
Issue Number: #230
Resolved: #
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/a3fb3f3b-fb08-4dcf-97f3-f1dc807c2d52
> [Feat] 마이페이지 크루 편집 화면 상세주소 설정 뷰 연결

- Carmu/Sources/Utils/FirebaseManager.swift
✅ Firebase의 crew -> memberStatus에 필요한 데이터가 업로드 되도록 하였습니다.
✅ 주석의 오타를 수정하였습니다.
Resolved: #273 
✅ crew -> crews는 삭제해도 될 것 같아 추후에 진행하면 될 것 같습니다.
✅ 초대 코드를 일시적으로 수정하여 버튼을 클릭하였을 때, 데이터가 업로드된 모습입니다. (deviceToken과 id는 가렸습니다.)
> [Feat] MemberStatus Firebase에 올리기

- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Utils/FirebaseManager.swift
✅ 앱을 껐다 켜도 해당 데이터에 맞는 UI가 나타나도록 설정하였습니다.
Resolved: #282 
✅ 이제 크루를 생성하고, 탑승자로 들어가있을 때 등을 확인해보실 수 있으니, 확인해봐주시고, 이상한 점이 있으면 말씀해주십시오.
✅ 크루의 상태 같은 경우에는 Firebase에서 값을 변경해줌으로써 설정하였습니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/bc399450-569c-4807-b308-65b5f9a70dda
> [Refactor] updateUI 시점 재구성

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/CrewMake/Driver/CrewNameSettingViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
- Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
- Carmu/Sources/Views/CrewMake/Driver/CrewNameSettingView.swift
크루 이름 생성하기 화면을 구현했습니다.
이에 따라 FinalConfirmView에서 크루 이름을 자동으로 생성해주는 부분을 삭제했습니다.
전체적인 코드는 InviteCodeInputView와 동일합니다.
아래의 gif를 참조하시면 되겠습니다.
Resolved: #285 
> [Feat] 크루 이름 생성하기 화면 구현

- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
네이버 맵 API를 사용하여 Geocoding 하는 방식으로 로직을 변경했습니다.
정확하지 않은 장소에 대해 데이터가 얻어지지 않는 문제를 해결하기 위해 버튼 처리를 동시에 진행했습니다.
Resolved: #286 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/9b9cca5c-e9ed-4139-bd81-b7b61185db99
> [Feat] reverseGeocoding Naver Map 활용으로 변경

- Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
✅ 데이터를 생성하면 바로 화면에 데이터가 나타나도록 설정하였습니다.
✅ addCrew 메서드에 sessionStatus 변수를 추가하였습니다.
Resolved: #279 
✅ 이슈가 있으나, 구두로 합의된 바와 같이 추후에 진행하도록 하겠습니다.
✅ 주석된 부분은 추후에 비교하면서 수정할 때 참고하고자 남겨두었습니다.
> [Feat] 크루 없을 때 -> 크루 생성하기 화면 연결

- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectAddressViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
- Carmu/Sources/Views/CrewMake/Driver/Cell/DefaultAddressTableViewCell.swift
- Carmu/Sources/Views/CrewMake/Driver/Cell/SelectAddressTableViewCell.swift
- Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectAddressView.swift
주소 검색 뷰에서 나타나는 검색 셀을 탭했을 때 하이라이트 되는 처리를 진행했습니다.
이와 더불어 출발/도착지 상세 위치를 설정할 때, 이동했음에도 처음 찍은 포인트가 나오는 버그를 수정했습니다.
이제 이동한 장소의 경도 위도가 최종적으로 데이터로 남게됩니다.
Resolved: #292 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/8af46ee4-8a71-4d78-a8cc-552d35593bdf
<셀 하이라이트 처리>
> [Feat] 주소 검색 화면 셀 탭 시 하이라이트 처리 기능 추가

- Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/CrewNameSettingViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
- Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
- Carmu/Sources/Controllers/LoginViewController.swift
- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Models/DTO/Crew.swift
- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
✅ setUserToCrew 메서드를 수정하였습니다.
- readUser에서 readUserAsync로 수정하였습니다.
✅ Observe 관련 코드 변경
- 기존의 코드는 데이터에 화면이 즉각적으로 반영되지 않아, 해당 레퍼런스의 값이 변경될 때마다 감지하도록 변경하였습니다. (childChanged -> value)
✅ crews 파라미터를 삭제하였고, 이와 관련된 코드들도 삭제하였습니다.
Resolved: #298 
> [Feat] 현재 나타나는 오류 수정

- Carmu/Sources/Controllers/Map/MapViewController.swift
- Carmu/Sources/Controllers/SessionStart/SessionFinishViewController.swift
- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Extensions/String+Extension.swift
- Carmu/Sources/Models/DTO/Crew.swift
- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/Map/MapDetailView.swift
셔틀 운행 종료 관련된 기능을 추가했습니다.
1. MapView에서 도착지 주변 200m 이내인 경우 15분 후에 얼럿을 띄우고 운행 종료하도록 수정
2. SessionStartView에서 도착지 도착 시간 + 지연 시간보다 10분 지났을 경우 종료 모달을 띄우도록 수정
세션이 종료되었을 때 세션 관련 데이터들(지연시간, 지각시간, 응답정보 등등)을 리셋
그 외 카풀용어들을 셔틀에 맞도록 수정했습니다.
Issue Number: #301 
Resolved: #301 
> [Feat] 도착 시간 10분 뒤 자동 종료

- Carmu/Sources/Controllers/SessionStart/RuleDescriptionViewController.swift
- Carmu/Sources/Models/Font/CarmuFont.swift
- Carmu/Sources/Views/SessionStart/RuleDescriptionView.swift
- Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
- Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
- Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
✅ 카드의 뒷면 부분을 설명하는 뷰로 일치시켰습니다.
- 기존에 하고자했던 뒷면 뷰는 constraint 설정 및 시간 이슈로 출시 후 진행하도록 합의되었습니다.
- 크루가 없을 때 나타내는 뷰로 변경하였습니다.
✅ BackView 안의 라벨을 수정하였습니다.
- 부가 설명을 추가하였습니다.
✅ 가이드 화면의 버튼을 변경하였습니다.
- 기존에 텍스트 "x"로 되어있던 버튼을 이미지로 변경하였습니다.
Resolved: #315 
[뒷면 화면]
<br>
<br>
[x버튼 이미지 변경]
> [feat] SessionStartBackView 변경 및 기타 작업 수정

- Carmu.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
- Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/MyPage/CrewEdit/CrewInfoCheckView.swift
- CrewInfoCheckViewController의 `updateCrewDataUI` 메서드에서 기존 point들이 들어 있는 스택 뷰를 비워준 뒤, 수정된 point들로 다시 채워주도록 했습니다.
- 우니가 `UIStackView`의 익스텐션으로 추가해놓으신 `removeAllArrangedSubviews()`를 활용했습니다.
- 운전자일 경우와 동승자일 경우 MyPageView에서 셔틀 그룹이 없는 화면이 나오도록 처리했습니다.
- 운전자의 경우에는 CrewInfoCheckViewController에서 셔틀 나가기를 누르기 때문에 셔틀 나가기가 완료되면 MyPageViewController로 돌아가지도록 했습니다.
- 초대코드를 입력하고 경유지를 선택해서 셔틀 그룹에 들어올 때 BoardingPointViewController 👉 SessionStartViewController로 진입하기 전 데이터 처리가 끝나야 화면처리 로직이 동작하도록 했습니다.
Issue Number: #307
Resolved: #307
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/eeda998d-e59a-4 …
> [Feat] 크루 편집 & 셔틀 나가기 & 초대코드로 셔틀 그룹 입장 시 화면 처리

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/Extensions/UIButton+Extension.swift
- Carmu/Sources/Models/Color/SemanticColor.swift
- Carmu/Sources/Views/SessionStart/SessionStartView.swift
✅ 함께가요, 따로가요 버튼에 대한 하이라이트를 적용하여 사용성을 고려하였습니다.
- 만약 버튼을 누르고 있으면 버튼의 색상이 변경됩니다.
- highlighted를 없애고 싶으면 해당 버튼의 isEnabled를 false로 변경해주면 됩니다.
Resolved: #324 
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/34651012-cbd3-436a-bb99-6a800d960225
> [Feat] 버튼 눌렀을 때 하이라이트 표시

- Carmu/Sources/Controllers/Map/MapViewController.swift
- Carmu/Sources/Utils/ServerPushManager.swift
✅ 운전자가 크루를 포기한 경우 탑승자들에게 푸시 알림을 보냅니다.
Resolved: #327 
> [feat] #327 - 운전자가 운전을 포기한 경우 탑승자들에게 푸시 알림

- Carmu/Sources/Controllers/Map/MapViewController.swift
- Carmu/Sources/Views/Map/MapView.swift
✅ 토스트 메세지가 한 화면에서 한 번만 뜨는 문제를 해결하였습니다.
- 뷰를 remove하는 부분을 삭제하였습니다.
Resolved: #337 
[iPhone 8]
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/db526924-ed1e-4571-9c18-5bdeb26506c7
<br>
<br>
[iPhone 14]
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/44b8dc8d-5ae6-413c-a8c8-67a8ee9cf5b1
> [fix] #337 - 토스트 메세지 한 번만 나타나고 나타나지 않는 문제 해결

- Carmu/Sources/AppDelegate.swift
- Carmu/Sources/Utils/FirebaseManager.swift
✅ 디바이스 토큰값이 변경되면 파이어베이스의 디바이스 토큰값 또한 갱신시켜줍니다.
- users의 디바이스 토큰, crew에 있는 디바이스 토큰값을 갱신해줍니다.
Resolved: #332 
> [feat] #332 - 디바이스 토큰값 변경되면 갱신하는 메서드 생성

- Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
- Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectView.swift
- Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
아이폰 8에서 대응이 되지 않던 화면을 수정했습니다.
UIScreen.main.bounds.height를 활용했습니다.
Resolved: #339 
<카드뷰 수정>
<반복요일 설정화면 아이폰 15 프맥>
<반복요일 설정화면 아이폰 8>
> [Fix] iPhone 8일 때의 Constraint 수정 

- Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
- Carmu/Sources/SceneDelegate.swift
메인화면인 StartView 호출시 로딩시간이 길어서 불필요한 버튼 및 하얀 화면이 너무 오래 보이는 문제가 있어 수정했습니다.
Issue Number: #334 
Resolved: #334 
BEFORE
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/22979718/710fa95b-17fd-4334-808e-bbeec65e5d5f
AFTER
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/22979718/1417a224-8778-4dbf-a44b-82ad63a2bcf3
> [Fix] StartView에서 로딩중일 때 완성되지 않은 화면이 보이고 있음

- Carmu/Sources/Utils/FirebaseManager.swift
Issue Number: #347 
Resolved: #347 
> [Fix] 따로가요, 함께가요 버튼 눌렀을시 Crash 발생하는 현상 수정

- Carmu/Sources/Utils/FirebaseManager.swift
Issue Number: #349 
Resolved: #349 
> [Fix] 크루 나가기 버튼 누를 때 Out of bound 에러 발생

- Carmu/Sources/Controllers/MyPage/NameEditViewController.swift
- Carmu/Sources/Utils/FirebaseManager.swift
마이 페이지에서 닉네임, 프로필이미지색상을 변경했을 때 crew안에 있는 memberStatus도 함께 수정되도록 구현했습니다.
Issue Number: #357 
Resolved: #357 
> [Feat] MyPage 수정시 Crew의 MemberStatus도 수정

- Carmu.xcodeproj/project.pbxproj
- Carmu/Sources/Controllers/CrewMake/Driver/CrewNameSettingViewController.swift
- Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
- Carmu/Sources/Controllers/MyPage/NameEditViewController.swift
- Carmu/Sources/Views/CrewMake/Driver/CrewNameSettingView.swift
- Carmu/Sources/Views/MyPage/NameEditView.swift
이름의 수식어가 ### 셔틀로 고정되도록 모든 뷰를 변경했습니다.
아래 영상 참고바랍니다.
Resolved: #359 
<만들기>
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/efe2e3bc-96a4-4d91-879d-ee2aedcbd197
<수정>
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/98330884/fc26ca1e-660b-479c-a7e5-6b85bd7731bb
> [Feat] 셔틀 이름 "000000 셔틀"로 생성되도록 기능 변경

- Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
- Carmu/Sources/Extensions/Bundle+Extension.swift
- `StoreKit`을 사용하면 인앱 리뷰로 남기게 할 수도 있는데 1년에 3번까지만 가능하다고 해서 일단은 앱스토어 앱으로 이동되도록 했습니다.
- 앱스토어 URL에 들어가는 AppID값은 `SecureKey-Info.plist` 파일에 추가해놨으니 디스코드 자료공유방을 참고해서 로컬에 받아주시면 되겠습니다.
- AppID를 불러오는 값은 Bundle+Extension.swift 에 정의되어 있습니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/8b67c817-8793-47d4-8d76-5ded83ae733c
Issue Number: #373
Resolved: #373
> [Feat] 문의하기 화면 앱스토어 리뷰 버튼 연결

- Carmu/Sources/Utils/LabelComponent/CarpoolPlanLabel.swift
- 셔틀 계획 보러가기 -> 셔틀 규칙 보러가기
Issue Number: #381 
Resolved: #381 
> [Fix] 메인 화면 문구 변경

- Carmu/Sources/Controllers/Map/MapViewController.swift
- Carmu/Sources/Views/Map/MapDetailView.swift
운전자가 셔틀 운행 중에 도착지 주변에 진입했다가 벗어나는 경우 버튼이 제대로 표시되지 않는 현상을 수정했습니다.
또한, 피그마에 적용된 버튼 폰트와 다른 부분이 있어 맞춰서 수정했습니다.
Issue Number: #375 
Resolved: #375 
수정 전
수정 후
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/22979718/4cd4fbac-5ff0-44b3-afde-37175358b9c8
> [Fix] 맵뷰 버튼이 제대로 표시되지 않음

- Carmu/Sources/Utils/FirebaseManager.swift
- Carmu/Sources/Views/Map/MapView.swift
> [Fix] 탑승자가 맵뷰 진입시 운전자의 위치가 바로 표시되지 않음
